### ISSUE TITLE
helpers 文件名 没有按照 psr-4 规范命名！

### ISSUE THREAD

**Issue by 2512422541** [donjan-deng/laravel-acm-client#2]

**Comment by Kevin-Ben** [comment]
Class Donjan\AcmClient\Helpers located in D:/www/xpx/vendor/donjan-deng/laravel-acm-client/src\helpers.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by Kevin-Ben** [comment]
请将`helpers.php`修改为`Helpers.php`
